list: $/indev/frontendformbuilder/models/fields/columns.yaml
modelClass: Indev\FrontEndFormBuilder\Models\Fields
title: FieldsController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'indev/frontendformbuilder/fieldscontroller/update/:id'
