list: $/indev/frontendformbuilder/models/formadvance/columns.yaml
modelClass: Indev\FrontEndFormBuilder\Models\FormAdvance
title: AdvanceFormController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'indev/frontendformbuilder/advanceformcontroller/update/:id'
