list: $/indev/frontendformbuilder/models/forntendformbuilder/columns.yaml
modelClass: Indev\FrontEndFormBuilder\Models\ForntendFormBuilder
title: FormbuilderController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'indev/frontendformbuilder/formbuildercontroller/update/:id'
